version: "3.7"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  postgres:
    <<: *logging

    container_name: postgres

    image: postgres:15-alpine

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 5

  api:
    <<: *logging

    container_name: api

    build:
      context: ./api
      dockerfile: Dockerfile

    env_file:
      - ./api/.env

    environment:
      POSTGRES_HOST: postgres

    volumes:
      - ./api:/api

    depends_on:
      - postgres

    ports:
      - "8000:8000"

  bot:
    <<: *logging

    container_name: bot

    build:
      context: ./bot
      dockerfile: Dockerfile

    env_file:
      - ./bot/.env

    environment:
      API_URL: "http://api:8000"

    depends_on:
      - api

    volumes:
      - ./bot:/bot
